
import { UserProfile, Workout, ProgressEntry } from '../types/fitness';

// Mock user profile data
export const mockUserProfile: UserProfile = {
  id: '1',
  name: 'John Doe',
  age: 28,
  height: 180,
  currentWeight: 85,
  startingWeight: 90,
  goalWeight: 80,
  goal: 'weightLoss',
  fitnessLevel: 'intermediate',
  profileImage: 'https://images.unsplash.com/photo-1500673922987-e212871fec22',
  bio: 'Fitness enthusiast looking to improve my overall health and build muscle.',
  joinDate: '2023-01-15',
};

// Mock workout data
export const mockWorkouts: Workout[] = [
  {
    id: '1',
    name: 'Full Body Strength',
    description: 'A comprehensive workout targeting all major muscle groups for overall strength gains.',
    duration: 45,
    intensity: 'moderate',
    category: 'strength',
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
    exercises: [
      {
        id: '101',
        name: 'Squats',
        description: 'A compound exercise that works your quads, hamstrings, and glutes.',
        sets: 3,
        reps: 12,
        muscleGroups: ['quads', 'hamstrings', 'glutes'],
      },
      {
        id: '102',
        name: 'Push-ups',
        description: 'A bodyweight exercise that targets your chest, shoulders, and triceps.',
        sets: 3,
        reps: 15,
        muscleGroups: ['chest', 'shoulders', 'triceps'],
      },
      {
        id: '103',
        name: 'Dumbbell Rows',
        description: 'An upper body exercise that strengthens your back and biceps.',
        sets: 3,
        reps: 12,
        muscleGroups: ['back', 'biceps'],
        equipment: ['dumbbells'],
      },
    ],
  },
  {
    id: '2',
    name: 'HIIT Cardio Blast',
    description: 'High-intensity interval training to boost metabolism and burn calories.',
    duration: 30,
    intensity: 'intense',
    category: 'cardio',
    imageUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843',
    exercises: [
      {
        id: '201',
        name: 'Jumping Jacks',
        description: 'A full-body cardio exercise.',
        duration: 45,
        muscleGroups: ['full-body'],
      },
      {
        id: '202',
        name: 'Mountain Climbers',
        description: 'A challenging cardio move that also engages your core.',
        duration: 45,
        muscleGroups: ['core', 'shoulders'],
      },
      {
        id: '203',
        name: 'Burpees',
        description: 'A full-body exercise that provides both strength and cardio benefits.',
        duration: 45,
        muscleGroups: ['full-body'],
      },
    ],
  },
  {
    id: '3',
    name: 'Core & Flexibility',
    description: 'Focus on building a strong core while improving overall flexibility.',
    duration: 35,
    intensity: 'light',
    category: 'flexibility',
    imageUrl: 'https://images.unsplash.com/photo-1649972904349-6e44c42644a7',
    exercises: [
      {
        id: '301',
        name: 'Plank',
        description: 'An isometric core exercise that improves stability.',
        duration: 60,
        muscleGroups: ['core', 'shoulders'],
      },
      {
        id: '302',
        name: 'Russian Twists',
        description: 'A rotational exercise that targets the obliques.',
        sets: 3,
        reps: 20,
        muscleGroups: ['obliques', 'core'],
      },
      {
        id: '303',
        name: 'Seated Forward Bend',
        description: 'A yoga pose that stretches the hamstrings and back.',
        duration: 60,
        muscleGroups: ['hamstrings', 'back'],
      },
    ],
  },
];

// Mock progress entries
export const mockProgressEntries: ProgressEntry[] = [
  {
    id: '1',
    userId: '1',
    date: '2023-04-01',
    weight: 90,
    photos: ['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158'],
    notes: 'Starting my fitness journey today!',
    mood: 'good',
    workouts: ['1'],
  },
  {
    id: '2',
    userId: '1',
    date: '2023-04-15',
    weight: 88.5,
    photos: ['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158'],
    notes: 'Feeling stronger already. Consistency is key.',
    mood: 'great',
    workouts: ['1', '2'],
    aiScore: 72,
    aiAnalysis: 'Good progress on weight loss. Form is improving but watch your posture during squats.',
  },
  {
    id: '3',
    userId: '1',
    date: '2023-05-01',
    weight: 87,
    photos: ['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158'],
    notes: 'One month in and down 3kg!',
    mood: 'great',
    workouts: ['2', '3'],
    aiScore: 78,
    aiAnalysis: 'Excellent progress! Weight loss is on track and muscle definition is starting to show.',
  },
  {
    id: '4',
    userId: '1',
    date: '2023-05-15',
    weight: 86,
    photos: ['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158'],
    notes: 'Struggled with motivation this week but pushed through.',
    mood: 'neutral',
    workouts: ['1'],
    aiScore: 75,
    aiAnalysis: 'Maintaining good progress. Focus on consistent water intake and sleep for better results.',
  },
  {
    id: '5',
    userId: '1',
    date: '2023-06-01',
    weight: 85,
    photos: ['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158'],
    notes: 'Two months in! Can definitely see changes in the mirror.',
    mood: 'great',
    workouts: ['1', '3'],
    aiScore: 82,
    aiAnalysis: 'Great improvement in overall physique. Core strength has significantly improved.',
  },
];
